version: "3"
services:
  back:
    image: cogeu/secret
    volumes:
      - /home/ubuntu/MA7/logs:/logs
    ports:
      - "3000:3000"
    env_file:
      - ./.env

  redis:
    image: redis:7.2.5
    volumes:
      - /home/ubuntu/MA7/redis:/usr/local/etc/redis
    env_file:
      - ./.env
    command: sh -c "redis-server /usr/local/etc/redis/redis.conf"
    ports:
      - "6379:6379"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/MA7/certbot/www:/var/www/certbot
      - /home/ubuntu/MA7/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/MA7/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/MA7/nginx/log:/var/log/nginx
    restart: always

  certbot:
    depends_on:
      - nginx
    image: certbot/certbot:latest
    volumes:
      - /home/ubuntu/MA7/certbot/www:/var/www/certbot
      - /home/ubuntu/MA7/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/MA7/certbot/log:/var/log/letsencrypt

    # 실제 서비스용 인증 발급
    entrypoint: "/bin/sh -c 'trap exit TERM; if [ ! -e /etc/letsencrypt/live/modern-world.shop/fullchain.pem ]; then certbot certonly --webroot --webroot-path=/var/www/certbot -d modern-world.shop -d api.modern-world.shop --email jo1814@naver.com --agree-tos --no-eff-email; fi; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    # 테스트용 인증 발급
    # entrypoint: "/bin/sh -c 'trap exit TERM; if [ ! -e /etc/letsencrypt/live/modern-world.shop/fullchain.pem ]; then certbot certonly --staging --webroot --webroot-path=/var/www/certbot -d modern-world.shop -d api.modern-world.shop --email jo1814@naver.com --agree-tos --no-eff-email; fi; while :; do certbot renew --staging; sleep 12h & wait $${!}; done;'"
