-- AlterTable
ALTER TABLE `neighbor` MODIFY `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- CreateTable
CREATE TABLE `alarm` (
    `no` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_no` INTEGER UNSIGNED NOT NULL,
    `content` VARCHAR(500) NOT NULL,
    `status` BOOLEAN NOT NULL DEFAULT false,
    `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `user_no`(`user_no`),
    PRIMARY KEY (`no`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `alarm` ADD CONSTRAINT `alarm_user_no_fkey` FOREIGN KEY (`user_no`) REFERENCES `user`(`no`) ON DELETE CASCADE ON UPDATE CASCADE;
