import { applyDecorators } from "@nestjs/common";
import {
  ApiBadRequestResponse,
  ApiInternalServerErrorResponse,
  ApiOkResponse,
  ApiOperation,
} from "@nestjs/swagger";

export function ApiGetCharacters() {
  return applyDecorators(
    ApiOperation({
      summary: "캐릭터 불러오기",
      description: "유저가 보유한 것과 상관없이 캐릭터만 불러옵니다.",
    }),

    ApiOkResponse({
      description: "Success",
      content: {
        JSON: {
          example: [
            {
              no: 1,
              name: "1번 cat 이름",
              description: "1번 cat 설명",
              image: "1번 cat 이미지",
              species: "cat",
              price: 100,
            },
            {
              no: 2,
              name: "2번 dog 이름",
              description: "2번 dog 설명",
              image: "2번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 3,
              name: "3번 cat 이름",
              description: "3번 cat 설명",
              image: "3번 cat 이미지",
              species: "cat",
              price: 100,
            },
            {
              no: 4,
              name: "4번 dog 이름",
              description: "4번 dog 설명",
              image: "4번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 5,
              name: "5번 dog 이름",
              description: "5번 dog 설명",
              image: "5번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 6,
              name: "6번 dog 이름",
              description: "6번 dog 설명",
              image: "6번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 7,
              name: "7번 dog 이름",
              description: "7번 dog 설명",
              image: "7번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 8,
              name: "8번 dog 이름",
              description: "8번 dog 설명",
              image: "8번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 9,
              name: "9번 dog 이름",
              description: "9번 dog 설명",
              image: "9번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 10,
              name: "10번 dog 이름",
              description: "10번 dog 설명",
              image: "10번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 11,
              name: "11번 cat 이름",
              description: "11번 cat 설명",
              image: "11번 cat 이미지",
              species: "cat",
              price: 100,
            },
            {
              no: 12,
              name: "12번 dog 이름",
              description: "12번 dog 설명",
              image: "12번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 13,
              name: "13번 dog 이름",
              description: "13번 dog 설명",
              image: "13번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 14,
              name: "14번 cat 이름",
              description: "14번 cat 설명",
              image: "14번 cat 이미지",
              species: "cat",
              price: 100,
            },
            {
              no: 15,
              name: "15번 dog 이름",
              description: "15번 dog 설명",
              image: "15번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 16,
              name: "16번 cat 이름",
              description: "16번 cat 설명",
              image: "16번 cat 이미지",
              species: "cat",
              price: 100,
            },
            {
              no: 17,
              name: "17번 dog 이름",
              description: "17번 dog 설명",
              image: "17번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 18,
              name: "18번 cat 이름",
              description: "18번 cat 설명",
              image: "18번 cat 이미지",
              species: "cat",
              price: 100,
            },
            {
              no: 19,
              name: "19번 cat 이름",
              description: "19번 cat 설명",
              image: "19번 cat 이미지",
              species: "cat",
              price: 100,
            },
            {
              no: 20,
              name: "20번 cat 이름",
              description: "20번 cat 설명",
              image: "20번 cat 이미지",
              species: "cat",
              price: 100,
            },
            {
              no: 21,
              name: "21번 dog 이름",
              description: "21번 dog 설명",
              image: "21번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 22,
              name: "22번 dog 이름",
              description: "22번 dog 설명",
              image: "22번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 23,
              name: "23번 dog 이름",
              description: "23번 dog 설명",
              image: "23번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 24,
              name: "24번 cat 이름",
              description: "24번 cat 설명",
              image: "24번 cat 이미지",
              species: "cat",
              price: 100,
            },
            {
              no: 25,
              name: "25번 dog 이름",
              description: "25번 dog 설명",
              image: "25번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 26,
              name: "26번 cat 이름",
              description: "26번 cat 설명",
              image: "26번 cat 이미지",
              species: "cat",
              price: 100,
            },
            {
              no: 27,
              name: "27번 cat 이름",
              description: "27번 cat 설명",
              image: "27번 cat 이미지",
              species: "cat",
              price: 100,
            },
            {
              no: 28,
              name: "28번 cat 이름",
              description: "28번 cat 설명",
              image: "28번 cat 이미지",
              species: "cat",
              price: 100,
            },
            {
              no: 29,
              name: "29번 dog 이름",
              description: "29번 dog 설명",
              image: "29번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 30,
              name: "30번 cat 이름",
              description: "30번 cat 설명",
              image: "30번 cat 이미지",
              species: "cat",
              price: 100,
            },
            {
              no: 31,
              name: "31번 dog 이름",
              description: "31번 dog 설명",
              image: "31번 dog 이미지",
              species: "dog",
              price: 100,
            },
            {
              no: 32,
              name: "32번 dog 이름",
              description: "32번 dog 설명",
              image: "32번 dog 이미지",
              species: "dog",
              price: 100,
            },
          ],
        },
      },
    }),

    ApiBadRequestResponse({
      description: "cat, dog 이외의 값을 넣었을 때",
      content: {
        JSON: {
          example: {
            message: ["species must be one of the following values: cat, dog"],
            error: "Bad Request",
            statusCode: 400,
          },
        },
      },
    }),

    ApiInternalServerErrorResponse({
      description: "Internal server error",
      content: {
        JSON: {
          example: {
            statusCode: 500,
            message: "Internal server error",
          },
        },
      },
    }),
  );
}
