name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
        - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull cogeu/secret:latest
    - name: Delete Old docker container
      run: sudo docker rm -f ma7-back-1 || true
    - name: Run Docker Container
      run: cd /home/ubuntu/MA7 | sudo docker compose up
