name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
        - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Delete Old docker container
      run: sudo docker rm -f ma7-back-1 || true
    - name: Pull Docker image
      run: sudo docker pull cogeu/secret:latest
    - name: Run Docker Container
      run: sudo docker-compose -f /home/ubuntu/MA7/docker-compose.yml up
