name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
        - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    

    - name: Delete Old docker container
      run: docker rm -f ma7-back || true
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD  
    - name: Pull Docker image
      run: docker pull cogeu/secret:latest
    - name: Run Docker Container
      run: docker-compose -f /home/ubuntu/MA7/docker-compose.yml up
