name: CD Pipeline Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types:
      - closed

jobs:
  build:
    runs-on: main

    if: github.event.pull_request.merged == true

    steps:
      - name: Delete Old docker container
        run: docker rm -f ma7-back-1 || true

      - name: Delete Old docker image
        run: docker rmi cogeu/secret || true

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Pull Docker image
        run: docker pull cogeu/secret:latest

      - name: Run Docker Container
        run: docker compose -f /home/ubuntu/MA7/docker-compose.yml up -d
